# Description: Gitlab CI/CD pipeline for FreeIPA
# SSH_USER SSH_PASSWORD SSH_HOST will be passed through the pipeline
stages:
  - check_env
  - configure-kcli-profiles
  - deploy-vm

check_env:
  stage: check_env
  image: python:3.10
  script:
    - python3 check_env.py

configure-kcli-profiles:
  stage: configure-kcli-profiles
  image: fedora:37
  variables:
    CICD_PIPELINE: "true"
    SSH_USER: admin
    TARGET_SERVER: "${TARGET_SERVER}"
  allow_failure: false
  script:
    - dnf install wget openssh-clients sshpass -y
    - mkdir -p ~/.ssh/
    - ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
    - sshpass -p "$SSH_PASSWORD" ssh-copy-id -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST"
    - ssh "$SSH_USER"@"$SSH_HOST"  'env CICD_PIPELINE="'$CICD_PIPELINE'" TARGET_SERVER="'$TARGET_SERVER'" bash -s' < configure-kcli-profiles.sh
  only:
    variables:
    - $JOB_TYPE == "configure-vm-profiles"

deploy-vm:
  stage: deploy-vm
  image: fedora:37
  variables:
    CICD_PIPELINE: "true"
    SSH_USER: admin
    TARGET_SERVER: "${TARGET_SERVER}"
    VM_NAME: "${VM_NAME}"
  allow_failure: false
  script:
    - dnf install wget openssh-clients sshpass -y
    - mkdir -p ~/.ssh/
    - ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
    - sshpass -p "$SSH_PASSWORD" ssh-copy-id -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST"
    - ssh "$SSH_USER"@"$SSH_HOST"  'env CICD_PIPELINE="'$CICD_PIPELINE'" TARGET_SERVER="'$TARGET_SERVER'  VM_NAME="'$VM_NAME'" bash -s' < deploy-vm.sh
  only:
    variables:
    - $JOB_TYPE == "deploy-vm"