stages:
  - check_env
  - configure-kcli-profiles
  - deploy-vm

check_env:
  stage: check_env
  tags:
    - shared
  script:
    - ls -lath .

configure-kcli-profiles:
  stage: configure-kcli-profiles
  tags:
    - shared
  variables:
    CICD_PIPELINE: "true"
    SSH_USER: admin
    TARGET_SERVER: "${TARGET_SERVER}"
  allow_failure: false
  script:
    - ls -lath .
  only:
    variables:
      - $JOB_TYPE == "configure-vm-profiles"

deploy-vm:
  stage: deploy-vm
  tags:
    - shared
  variables:
    CICD_PIPELINE: "true"
    SSH_USER: "${SSH_USER}"
    TARGET_SERVER: "${TARGET_SERVER}"
    VM_NAME: "${VM_NAME}"
    VM_PROFILE: "${VM_PROFILE}"
    ACTION: "${ACTION}"
  allow_failure: false
  script:
    - ls -lath .
  only:
    variables:
      - $JOB_TYPE == "deploy-vm"
