DEFAULT_PASSWORD: "your_default_password"
DEFAULT_GIT_URL: "gitlab.examplec.com:8443"
DEFAULT_GIT_REPO: "https://gitlab.examplec.com:8443/takinosh/kcli-pipelines.git"
DEFAULT_CICD_PIPELINE: "true"
DEFAULT_TARGET_SERVER: "rhel9-equinix"
DEFAULT_PRIVATE_TOKEN: "glptt-XXXXXXXXX"
DEFAULT_VM_PROFILE: "freeipa"
DEFAULT_ACTION: "create"
DEFAULT_COMMUNITY_VERSION: "false"
DEFAULT_DEPLOY_OPENSHIFT: "yes"
DEFAULT_LAUNCH_STEPS: "Deploy VM"
DEFAULT_TAG: "4.16"
DEFAULT_DISCONNECTED_INSTALL: "no"
DEFAULT_DEPLOYMENT_CONFIG: "cnv-kcli-openshift4-baremetal.yml"
DEFAULT_GUID: "q4hjb"
DEFAULT_IP_ADDRESS: "192.168.1.1"
DEFAULT_ZONE_NAME: "default_zone"
DEFAULT_VERBOSE_LEVEL: "vvv"
DEFAULT_PROJECT_ID: "1"
DEFAULT_REF: "main"  # Add the default ref here
