DEFAULT_PASSWORD: "your_default_password"
DEFAULT_GIT_URL: "gitlab.example.com:8443"
DEFAULT_GIT_REPO: "https://gitlab.example.com:8443/takinosh/kcli-pipelines.git"
DEFAULT_CICD_PIPELINE: "true"
DEFAULT_TARGET_SERVER: "rhel9-equinix"
DEFAULT_PRIVATE_TOKEN: "glptt-XXXXXXXXX"
DEFAULT_VM_PROFILE: "freeipa"
DEFAULT_ACTION: "create"
DEFAULT_COMMUNITY_VERSION: "false"
DEFAULT_DEPLOY_OPENSHIFT: "yes"
DEFAULT_LAUNCH_STEPS: "Deploy VM"
DEFAULT_TAG: "4.16"
DEFAULT_DISCONNECTED_INSTALL: "no"
DEFAULT_INITIAL_PASSWORD: "your_default_password"
DEFAULT_DEPLOYMENT_CONFIG: "cnv-kcli-openshift4-baremetal.yml"
DEFAULT_GUID: "123fs"
DEFAULT_IP_ADDRESS: "192.168.1.1"
DEFAULT_DOMAIN: "xxx.example.com"
DEFAULT_ZONE_NAME: "xxx.example.com"
DEFAULT_VERBOSE_LEVEL: "vvv"
DEFAULT_PROJECT_ID: "1"
DEFAULT_REF: "main"  # Add the default ref here
DEFAULT_HARBOR_VERSION: "2.5.0"
DEFAULT_QUAY_VERSION: "3.6.0"
DEFAULT_STEP_CA_PASSWORD: "default_step_ca_password"
