kube-ctrl01:
  memory: 16384
  numcpus: 4
  reservedns: true
  disks:
  - size: 200
  nets:
    - name: qubinet
  pool: default
  image: ubuntu
  cmds:
  - echo "ubuntu:CHANGEPASSWORD" | sudo chpasswd
  - apt update -y 
  - apt install -y git 
  - cd /home/ubuntu
  - git clone https://github.com/tosin2013/kubernetes_deployment.git
  - chown ubuntu:ubuntu -R ~/kubernetes_deployment
kube-worker1:
  memory: 16384
  numcpus: 4
  disks:
  - size: 200
  nets:
    - name: qubinet
  pool: default
  image: ubuntu
  cmds:
  - echo "ubuntu:CHANGEPASSWORD" | sudo chpasswd
  - apt update -y 
kube-worker2:
  memory: 16384
  numcpus: 4
  disks:
  - size: 200
  nets:
    - name: qubinet
  pool: default
  image: ubuntu
  cmds:
  - echo "ubuntu:CHANGEPASSWORD" | sudo chpasswd
  - apt update -y 
