name: Deploy VMs on KVM
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'hostname'
        required: true
        default: hostname
      target_server:
        description: 'target_server'
        required: true
        default: rhel8-equinix
      action:
        description: 'action'
        required: true
        default: create
        type: choice
        options:
          - create
          - delete
      vm_name:
        description: 'VM Deployment'
        required: true
        default: 'freeipa'
        type: choice
        options:
          - freeipa
          - freeipa-server-container
          - mirror-registry
          - microshift-demos
          - openshift-jumpbox
          - device-edge-workshops
          - ansible-aap
          - rhel8
          - rhel9
          - ocp4-disconnected-helper
      runner:
        description: 'Runner'
        required: true
        default: 'self-hosted'
      runner_name:
        description: 'Self-hosted runner name'
        required: true
        default: 't9rq8-github-runner' 
env:
    TARGET_SERVER: ${{ inputs.target_server }}
    VM_NAME: ${{ inputs.vm_name }}
    ACTION: ${{ inputs.action }}
    RUNNER: ${{ inputs.runner }}
   
jobs:
  deploy-vm:
    runs-on: ${{ inputs.runner_name }} # Directly use the runner name
    timeout-minutes: 45
    if: ${{ inputs.runner == 'self-hosted'  }}
    steps:
    - name: Deploying  ${{ inputs.vm_name }} on KVM
      runs-on: ${{ inputs.runner_name }}
      script: | 
          sudo yum install -y git
          if [ -d "/home/runner/kcli-pipelines" ]; then
            cd /home/runner/kcli-pipelines
            git config pull.rebase false
            git pull
          else
            cd /home/runner
            git clone https://github.com/tosin2013/kcli-pipelines.git
          fi
          export TARGET_SERVER=${{ env.TARGET_SERVER }}
          export VM_NAME=${{ env.VM_NAME }}
          export VM_PROFILE=${{ env.VM_NAME }}
          export ACTION=${{ env.ACTION }}
          /home/runner/kcli-pipelines/deploy-vm.sh
