name: Deploy VMs on KVM
on:
  workflow_dispatch:
    inputs:
      target_server:
        description: 'Target server'
        required: true
        default: rhel9-equinix
      action:
        description: 'Action'
        required: true
        default: create
        type: choice
        options:
          - create
          - delete
      vm_name:
        description: 'VM Deployment'
        required: true
        default: 'freeipa'
        type: choice
        options:
          - freeipa
          - freeipa-server-container
          - mirror-registry
          - microshift-demos
          - openshift-jumpbox
          - device-edge-workshops
          - ansible-aap
          - rhel8
          - rhel9
          - ocp4-disconnected-helper
      runner:
        description: 'Runner'
        required: true
        default: 'self-hosted'
      runner_name:
        description: 'Self-hosted runner name'
        required: true
        default: 't9rq8-github-runner'
      community_version:
        description: 'Use community version of software (true/false)'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      custom_vm_name:
        description: 'Custom VM Name (Only applicable if VM Deployment is not freeipa)'
        required: false
        default: ''

env:
  TARGET_SERVER: ${{ inputs.target_server }}
  VM_NAME: ${{ inputs.vm_name }}
  ACTION: ${{ inputs.action }}
  RUNNER: ${{ inputs.runner }}
  COMMUNITY_VERSION: ${{ inputs.community_version }}
  DEFAULT_RUNNER_USER: "runner"


jobs:
  configure-kcli-profiles:
    runs-on: self-hosted # Use the runner name at the job level
    timeout-minutes: 30
    if: ${{ inputs.runner == 'self-hosted' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure kcli profiles
        run: | 
          export TARGET_SERVER=${{ env.TARGET_SERVER }}
          export VM_PROFILE=${{ env.VM_NAME }}
          if [ "${{ inputs.vm_name }}" != "freeipa" ]; then
            export CUSTOM_PROFILE=false
          else 
            export CUSTOM_PROFILE=true
          fi
          if [ -d "/opt/kcli-pipelines" ]; then
            cd /opt/kcli-pipelines
            git config pull.rebase false
            git pull
          else
            cd /opt/
            git clone https://github.com/tosin2013/kcli-pipelines.git
          fi
          sudo -E /opt/kcli-pipelines/configure-kcli-profiles.sh || exit $?

  deploy-vm:
    runs-on: self-hosted # Use the runner name at the job level
    timeout-minutes: 45
    needs: configure-kcli-profiles # Ensure the previous job runs first
    if: ${{ inputs.runner == 'self-hosted' }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploying ${{ inputs.vm_name }} on KVM
        run: | 
          if [ -d "/opt/kcli-pipelines" ]; then
            cd /opt/kcli-pipelines
            git config pull.rebase false
            git pull
          else
            cd /opt
            git clone https://github.com/tosin2013/kcli-pipelines.git
          fi
          export TARGET_SERVER=${{ env.TARGET_SERVER }}
          export VM_NAME=${{ env.VM_NAME }}
          export VM_PROFILE=${{ env.VM_NAME }}
          export ACTION=${{ env.ACTION }}
          if [ "${{ inputs.vm_name }}" != "freeipa" ] && [ "${{ inputs.custom_vm_name }}" != "" ]; then
            export VM_NAME=${{ inputs.custom_vm_name }}
          fi
          sudo -E /opt/kcli-pipelines/deploy-vm.sh
