name: Deploy Registry
on:
  workflow_dispatch:
    inputs:
      target_server:
        description: 'Target server'
        required: true
        default: rhel9-equinix
      action:
        description: 'Action'
        required: true
        default: create
        type: choice
        options:
          - create
          - delete
      vm_name:
        description: 'VM Deployment'
        required: true
        default: 'freeipa'
        type: choice
        options:
          - harbor
          - mirror-registry
      harbor_version:
        description: 'Harbor version'
        required: true
        default: 'v2.11.1'
      quay_version:
        description: 'Quay version'
        required: true
        default: 'v3.12.3'
      runner:
        description: 'Runner'
        required: true
        default: 'self-hosted'
      runner_name:
        description: 'Self-hosted runner name'
        required: true
        default: 't9rq8-github-runner'
      community_version:
        description: 'Use community version of software (true/false)'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

env:
  TARGET_SERVER: ${{ inputs.target_server }}
  VM_NAME: ${{ inputs.vm_name }}
  ACTION: ${{ inputs.action }}
  RUNNER: ${{ inputs.runner }}
  COMMUNITY_VERSION: ${{ inputs.community_version }}
  DEFAULT_RUNNER_USER: "runner"
  HARBOR_VERSION: ${{ inputs.harbor_version }}
  QUAY_VERSION: ${{ inputs.quay_version }}


jobs:
  configure-kcli-profiles:
    runs-on: self-hosted # Use the runner name at the job level
    timeout-minutes: 30
    if: ${{ inputs.runner == 'self-hosted' }}
    steps:
      - uses: actions/checkout@v3

      - name: Check permissions
        run: |
          if [ -d "/opt/kcli-pipelineskcli-pipelines" ]; then
            ls -la /opt/kcli-pipelineskcli-pipelines/.git
            sudo chown -R ${{ env.DEFAULT_RUNNER_USER }}:${{ env.DEFAULT_RUNNER_USER }} /opt/kcli-pipelineskcli-pipelines
          fi


      - name: Configure kcli profiles
        run: | 
          export TARGET_SERVER=${{ env.TARGET_SERVER }}
          export VM_PROFILE=${{ env.VM_NAME }}
          if [ "${{ inputs.vm_name }}" != "freeipa" ]; then
            export CUSTOM_PROFILE=false
          else 
            export CUSTOM_PROFILE=true
          fi
          if [ -d "/opt/kcli-pipelineskcli-pipelines" ]; then
            ls -la /opt/kcli-pipelineskcli-pipelines/.git
            sudo chown -R ${{ env.DEFAULT_RUNNER_USER }}:${{ env.DEFAULT_RUNNER_USER }} /opt/kcli-pipelineskcli-pipelines
          fi
          if [ -d "/opt/kcli-pipelineskcli-pipelines" ]; then
            cd /opt/kcli-pipelineskcli-pipelines
            git config pull.rebase false
            git pull
          else
            cd /opt/kcli-pipelines
            git clone https://github.com/tosin2013/kcli-pipelines.git
          fi
          sudo -E /opt/kcli-pipelineskcli-pipelines/configure-kcli-profiles.sh || exit $?

  deploy-dns:
    runs-on: self-hosted # Use the runner name at the job level
    timeout-minutes: 45
    needs: configure-kcli-profiles # Ensure the previous job runs first
    if: ${{ inputs.runner == 'self-hosted' }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploying freeipa on KVM
        run: | 
          if [ -d "/opt/kcli-pipelineskcli-pipelines" ]; then
            cd /opt/kcli-pipelineskcli-pipelines
            git config pull.rebase false
            git pull
          else
            cd /home/${{ env.DEFAULT_RUNNER_USER }}
            git clone https://github.com/tosin2013/kcli-pipelines.git
          fi
          export TARGET_SERVER=${{ env.TARGET_SERVER }}
          export VM_PROFILE=freeipa
          export ACTION=${{ env.ACTION }}
          export VM_NAME=freeipa
          sudo -E /opt/kcli-pipelineskcli-pipelines/deploy-vm.sh

  deploy-registry-vm:
    runs-on: self-hosted # Use the runner name at the job level
    timeout-minutes: 45
    needs: deploy-dns # Ensure the previous job runs first
    if: ${{ inputs.runner == 'self-hosted' }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploying ${{ inputs.vm_name }} on KVM
        run: | 
          if [ -d "/opt/kcli-pipelineskcli-pipelines" ]; then
            cd /opt/kcli-pipelineskcli-pipelines
            git config pull.rebase false
            git pull
          else
            cd /home/${{ env.DEFAULT_RUNNER_USER }}
            git clone https://github.com/tosin2013/kcli-pipelines.git
          fi
          export TARGET_SERVER=${{ env.TARGET_SERVER }}
          export VM_NAME=${{ env.VM_NAME }}
          export VM_PROFILE=${{ env.VM_NAME }}
          export ACTION=${{ env.ACTION }}
          export HARBOR_VERSION=${{ env.HARBOR_VERSION }}
          export QUAY_VERSION=${{ env.QUAY_VERSION }}
          if [ "${{ inputs.vm_name }}" != "freeipa" ]; then
            export VM_NAME=${{ inputs.vm_name }}
          fi
          /opt/kcli-pipelineskcli-pipelines/deploy-vm.sh
