name: Deploy kcli-openshift4-baremetal instances on KVM
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'hostname'
        required: true
        default: hostname
      deployment_config:
        description: 'Supported Deployment Configurations'
        required: true
        default: 'cnv-kcli-openshift4-baremetal.yml'
        type: choice
        options:
          - cnv-kcli-openshift4-baremetal.yml
          - convereged-kcli-openshift4-baremetal.yml
          - kcli-openshift4-baremetal.yml
      target_server:
        description: 'target_server'
        required: true
        default: rhel8-equinix
      vm_name:
        description:  'VM Deployment'
        required: true
        default: kcli-openshift4-baremetal
      action:
        description: 'action'
        required: true
        default: create
        type: choice
        options:
          - create
          - delete
      deploy_openshift:
        description: 'Deploy The OpenShit Cluster on Launch'
        required: true
        default: true
        type: choice
        options:
          - true
          - false
      auto_launch_steps:
        description: 'Auto deploy Steps'
        required: true
        default: true
        type: choice
        options:
          - true
          - false
      deployment_tag:
        description: 'OpenShift Version'
        required: true
        default: '4.15'
        type: choice
        options:
          - '4.13'
          - '4.14'
          - '4.15'
      disconnected_install:
        description: 'Enable Disconnected Install'
        required: true
        default: false
        type: choice
        options:
          - true
          - false
env:
    TARGET_SERVER: ${{ inputs.target_server }}
    VM_NAME: ${{ inputs.vm_name }}
    ACTION: ${{ inputs.action }}
    DEPLOY_OPENSHIFT: ${{ inputs.deploy_openshift }}
    LAUNCH_STEPS: ${{ inputs.auto_launch_steps }}
    TAG: ${{ inputs.deployment_tag }}
    DISCONNECTED_INSTALL: ${{ inputs.disconnected_install }}
    DEPLOYMENT_CONFIG: ${{ inputs.deployment_config }}

jobs:
  configure-kcli-profiles:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: configuring kcli profiles
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ inputs.hostname }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            sudo yum install -y git
            if [ -d "/opt/kcli-pipelines" ]; then
              cd /opt/kcli-pipelines
              git config pull.rebase false
              git pull
            else
              cd /opt/
              git clone https://github.com/tosin2013/kcli-pipelines.git
            fi
            export TARGET_SERVER=${{ env.TARGET_SERVER }}
            export VM_PROFILE=${{ env.VM_NAME }}
            /opt/kcli-pipelines/configure-kcli-profiles.sh
  kcli-openshift4-baremetal:
    needs: configure-kcli-profiles
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - name: Deploying  ${{ inputs.vm_name }} on KVM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.hostname }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 90m
        script: | 
          sudo yum install -y git
          if [ -d "/opt/kcli-pipelines" ]; then
            cd /opt/kcli-pipelines
            git config pull.rebase false
            git pull
          else
            cd /opt/
            git clone https://github.com/tosin2013/kcli-pipelines.git
          fi
          export TARGET_SERVER=${{ env.TARGET_SERVER }}
          export VM_NAME=${{ env.VM_NAME }}
          export VM_PROFILE=${{ env.VM_NAME }}
          export ACTION=${{ env.ACTION }}
          export DEPLOY_OPENSHIFT=${{ env.DEPLOY_OPENSHIFT }}
          export LAUNCH_STEPS=${{ env.LAUNCH_STEPS }}
          export TAG=${{ env.TAG }}
          export DISCONNECTED_INSTALL=${{ env.DISCONNECTED_INSTALL }}
          export DEPLOYMENT_CONFIG=${{ env.DEPLOYMENT_CONFIG }}
          /opt/kcli-pipelines/deploy-vm.sh
