name: Scheduled Deployment

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every four hours at minute 0
  workflow_dispatch:
    inputs:
      runner_tag:
        description: 'Runner'
        required: true
        default: 'z2r22-github-runner'
        type: string
      action:
        description: 'Action'
        required: true
        default: 'create'
        type: string


jobs:
  clean-up-deploy-registry:
    uses: ./.github/workflows/deploy-registry-workflow-call.yaml
    with:
      target_server: 'rhel9-equinix'
      vm_name: 'harbor'
      action: delete
      harbor_version: 'v2.11.1'
      quay_version: 'v3.12.3'
      email: 'vasaga9759@craftapk.com'
      guid: 'z2r22'
      runner_tag: ${{ inputs.runner_tag }}
      community_version: false

  deploy-registry:
    needs: clean-up-deploy-registry
    uses: ./.github/workflows/deploy-registry-workflow-call.yaml
    with:
      target_server: 'rhel9-equinix'
      vm_name: 'harbor'
      action: ${{ inputs.action }}
      harbor_version: 'v2.11.1'
      quay_version: 'v3.12.3'
      email: 'vasaga9759@craftapk.com'
      guid: 'z2r22'
      runner_tag: ${{ inputs.runner_tag }}
      community_version: false


  configure-ocp4-disconnected-helper:
    needs: deploy-registry
    uses: ./.github/workflows/configure-ocp4-disconnected-helper-workflow-call.yaml
    with:
      target_server: 'rhel9-equinix'
      action: ${{ inputs.action }}
      guid: 'z2r22'
      runner_tag: ${{ inputs.runner_tag }}
      DOWNLOAD_TO_TAR: 'true'  # Passed as string
      PUSH_TAR_TO_REGISTRY: 'true'
      HARBOR_PASSWORD: Harbor12345  # Passed as string
