name: Scheduled Deployment

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every five minutes
  workflow_dispatch:
    inputs:
      runner_tag:
        description: 'Runner'
        required: true
        default: 'z2r22-github-runner'  # Ensure default value is set
        type: string
      guid:
        description: 'GUID'
        required: true
        default: 'z2r22'
        type: string
      action:
        description: 'Action'
        required: true
        default: 'create' 
        type: string

jobs:
  clean-up-deploy-registry:
    uses: ./.github/workflows/deploy-registry-workflow-call.yaml
    with:
      target_server: 'rhel9-equinix'
      vm_name: 'harbor'
      action: delete
      harbor_version: 'v2.11.1'
      quay_version: 'v3.12.3'
      email: 'vasaga9759@craftapk.com'
      guid: ${{ github.event_name == 'schedule' && 'z2r22' || inputs.guid }}
      runner_tag: ${{ github.event_name == 'schedule' && 'z2r22-github-runner' || inputs.runner_tag }}
      community_version: false

  deploy-registry:
    needs: clean-up-deploy-registry
    uses: ./.github/workflows/deploy-registry-workflow-call.yaml
    with:
      target_server: 'rhel9-equinix'
      vm_name: 'harbor'
      action: ${{ inputs.action }}
      harbor_version: 'v2.11.1'
      quay_version: 'v3.12.3'
      email: 'vasaga9759@craftapk.com'
      guid: ${{ github.event_name == 'schedule' && 'z2r22' || inputs.guid }}
      runner_tag: ${{ github.event_name == 'schedule' && 'z2r22-github-runner' || inputs.runner_tag }}
      community_version: false


  configure-ocp4-disconnected-helper:
    needs: deploy-registry
    uses: ./.github/workflows/configure-ocp4-disconnected-helper-workflow-call.yaml
    with:
      target_server: 'rhel9-equinix'
      action: ${{ inputs.action }}
      guid: ${{ github.event_name == 'schedule' && 'z2r22' || inputs.guid }}
      runner_tag: ${{ github.event_name == 'schedule' && 'z2r22-github-runner' || inputs.runner_tag }}
      DOWNLOAD_TO_TAR: 'true'  # Passed as string
      PUSH_TAR_TO_REGISTRY: 'true'
      HARBOR_PASSWORD: Harbor12345  # Passed as string
