name: Scheduled Deployment

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every four hours at minute 0
  workflow_dispatch:
    inputs:
      runner_tag:
        description: 'Runner'
        required: true
        default: z2r22-github-runner
        type: string
      action:
        description: 'Action'
        required: true
        default: create
        type: string
        options:
          - create
          - delete

jobs:
  deploy-registry:
    uses: ./.github/workflows/workflow_calls/deploy-registry.yaml
    with:
      target_server: 'rhel9-equinix'
      vm_name: 'freeipa'
      action: ${{ inputs.action }}
      harbor_version: 'v2.11.1'
      quay_version: 'v3.12.3'
      email: 'vasaga9759@craftapk.com'
      guid: 'mjffm'
      runner_tag: ${{ inputs.runner_tag }}
      community_version: 'false'

  configure-helper:
    needs: deploy-registry
    uses: ./.github/workflows/configure-ocp4-disconnected-helper.yaml
    with:
      target_server: 'rhel9-equinix'
      action: ${{ inputs.action }}
      guid: 'mjffm'
      runner_tag: ${{ inputs.runner_tag }}
      DOWNLOAD_TO_TAR: 'true'
      PUSH_TAR_TO_REGISTRY: 'true'
      SETUP_QUAY_REGISTRY: 'false'
      SETUP_HARBOR_REGISTRY: 'false'  # Corrected typo
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}  # Secured password

  deploy-openshift:
    needs: configure-helper
    uses: ./.github/workflows/kcli-openshift4-baremetal-external.yaml
    with:
      deployment_config: 'cnv-kcli-openshift4-baremetal.yml'
      target_server: 'rhel9-equinix'
      vm_name: 'kcli-openshift4-baremetal'
      action: ${{ inputs.action }}
      deploy_openshift: 'true'
      auto_launch_steps: 'true'
      deployment_tag: '4.17'
      disconnected_install: 'false'
      community_version: 'false'
      runner_tag: ${{ inputs.runner_tag }}
